### PR TITLE
Refactoring hardcoded values to be configurable from env variables

### PR DESCRIPTION
**Pull request by pacostas**
Some values are hardcoded. IMO they should be configurable from the env variables and as a fallback having the current hardcoded value.

### CODE REVIEW

**Comment by helio-frota** [comment]
The idea is to have random topic names and groups via command line?

Sorry, I'm not following.

For example the demo https://github.com/nodeshift-starters/reactive-koffeeshop-demo is about `beverages`.
And this example is about `countries`,

So by using `const topic = process.env.KAFKA_TOPIC || 'countries';`

We are kind of saying that this demo could be about `cars`, `animals`, `flowers` etc...
without mention that the front-end part is making that hard coded:

`<h2>Received countries:</h2>` 
https://github.com/nodeshift-starters/reactive-example/blob/kafkajs/frontend/public/index.html#L13

IMO we can keep with no env vars unless we are having issues with some deployment etc :+1:

**Comment by helio-frota** [comment]
And ofc the back-end https://github.com/nodeshift-starters/reactive-example/blob/kafkajs/producer-backend/producer.js#L38

https://chancejs.com/location/country.html

**Comment by pacostas** [comment]
I see... In that case I would suggest documenting the goal or use case of the implementation on the readme file, instead of altering common patterns to communicate that info, which might end up being interpreted wrong.

**Comment by helio-frota** [comment]
> I see... In that case I would suggest documenting the goal or use case of the implementation on the readme file, instead of altering common patterns to communicate that info, which might end up being interpreted wrong.

I'm sorry I'm still now following. 
The env var for the topic is something required for an deployment or something?
I mean if the producer is producing `countries` why to have a topic called let's say `foods`?

**Comment by pacostas** [comment]
> The env var for the topic is something required for an deployment or something?

Yes, in case you want to have two implementations with the same broker.

> I mean if the producer is producing `countries` why to have a topic called let's say `foods`?

Foods doesn't make sense, usually you would have something like countries-dev, countries-staging

**Review by helio-frota — APPROVED** [review]

**Pull request merged**
