### PR TITLE
Adding gitignore

### PR DESCRIPTION
**Pull request by pacostas**
Adding gitignore and adding also rhoas.env to gitignore

### CODE REVIEW

**Review by helio-frota — CHANGES_REQUESTED** [review]
@pacostas I have nothing against the commit messages without the prefix `chore:` since we are not going to release this repo etc...I mean not a blocker but after some years in the team following that practice I can share that yeah that helped to look commits later when using `git log --oneline`

other thing -- not a blocker for me -- to have a lot of stuff in a `.gitignore` file 
but in other hand I start to think that it make no sense at all to have things that we probably never will use 

maybe just add the `rhoas.env` and keep the thing concise as possible is the best option.

**Comment by pacostas** [comment]
> @pacostas I have nothing against the commit messages without the prefix `chore:` since we are not going to release this repo etc...I mean not a blocker but after some years in the team following that practice I can share that yeah that helped to look commits later when using `git log --oneline`

I agree, I changed it from `fix:` to `chore:`

> other thing -- not a blocker for me -- to have a lot of stuff in a `.gitignore` file but in other hand I start to think that it make no sense at all to have things that we probably never will use

> maybe just add the `rhoas.env` and keep the thing concise as possible is the best option.

I removed as much as possible, almost half of the file size.

**Comment by helio-frota** [comment]
> I removed as much as possible, almost half of the file size.

@pacostas thanks :+1: 

Also `.gitignore` can be seen as "historical reasons"
IMO this is another thing that when used concisely can help to understand things from the past.

For example: 
https://github.com/nodeshift-starters/nodejs-rest-http/commits/main/.gitignore

1) Luke was the author of the boosters/examples and he was using Mac in that time

```
node_modules/
#System Files
.DS_Store
Thumbs.db
```

2) He was working later on a nodeshift deployment feature and it was required to add the `tmp` directory

3) Years later I added more bits related to some changes in CI usage

```
.nyc_output/
coverage/
```

**Comment by pacostas** [comment]
I agree, we can add more stuff in case we need to. Right now I cant think something on the top of my head. Let me know if you think it would be valuable to add these too:
```
node_modules/
#System Files
.DS_Store
Thumbs.db
```

**Comment by helio-frota** [comment]
> I agree, we can add more stuff in case we need to.

Agree, and in that spirit, a quick question: Are you using this?

`rpt2_cache`

**Comment by helio-frota** [comment]
Other thing is, I'm not sure if you noticed that we already have a `.gitignore` file :+1: 

https://github.com/nodeshift-starters/reactive-example/blob/kafkajs/.gitignore

**Comment by pacostas** [comment]
> #System Files
> .DS_Store
> Thumbs.db

**Comment by pacostas** [comment]
> Other thing is, I'm not sure if you noticed that we already have a `.gitignore` file +1
> 
> https://github.com/nodeshift-starters/reactive-example/blob/kafkajs/.gitignore

Yes, this PR applies to this file.

**Comment by pacostas** [comment]
> > I agree, we can add more stuff in case we need to.
> 
> Agree, and in that spirit, a quick question: Are you using this?
> 
> `rpt2_cache`

No ATM

**Comment by pacostas** [comment]
> I agree, we can add more stuff in case we need to. Right now I cant think something on the top of my head. Let me know if you think it would be valuable to add these too:
> 
> ```
> node_modules/
> #System Files
> .DS_Store
> Thumbs.db
> ```

Added it.

**Comment by pacostas** [comment]
@helio-frota are we good to land it?

**Comment by helio-frota** [comment]
@pacostas so according to the previous conversations I was thinking that we agreed to add only the things we are using.

Here you can see the original and the new content:



It would be good to add the required things only, as you suggested in your first comment:



:+1:

**Comment by pacostas** [comment]
Force Pushed with Helio's suggestions

**Pull request merged**
